name: Deploy to Hatchbox on Successful 'gh signoff' Check

# This workflow deploys code to Hatchbox when a specific 'signoff' check run,
# typically created by a tool like 'gh signoff' (https://github.com/basecamp/gh-signoff),
# completes successfully for a commit. It uses the official Hatchbox Deploy Action.
#
# How it works:
# 1. Trigger: Activates when a 'check_run' event occurs with the type 'completed'.
# 2. Conditions for running the deployment job:
#    - The completed check run's name must start with "signoff" (e.g., "signoff - Your Name signed off").
#    - The conclusion of this "signoff" check run must be 'success'.
#    - The check run should ideally be associated with a pull request.
# 3. Deployment:
#    - It uses the 'hatchboxio/github-hatchbox-deploy-action@v2' to trigger the deployment.
#    - It deploys the specific commit SHA (`head_sha`) associated with the successful "signoff" check run.
# 4. Secrets:
#    - `HATCHBOX_DEPLOY_KEY`: You must configure this secret in your GitHub repository settings.
#      It's the deploy key provided by Hatchbox for webhook deployments.
#      (See Hatchbox documentation: App -> Settings -> Deployments -> Webhook URL, or their action marketplace page).
#
# Integration with 'gh signoff' CLI or similar tools:
# This workflow is designed to work in conjunction with tools or processes that
# update a commit's status via GitHub Checks API, specifically creating a check run
# named starting with "signoff". When you run `gh signoff` locally for a commit,
# and it reports success to GitHub by creating/updating a check run, this workflow
# will detect the successful completion of that specific "signoff" check and proceed to deploy.
#
# Important Considerations:
# - Ensure that the "signoff" check is configured to run or be reported only after
#   all other necessary checks (tests, linting, security scans) have passed for the commit.
#   This workflow deploys based on the success of the "signoff" check alone.
# - The deployment will always be for the specific commit that the "signoff" check passed on.

on:
  # check_run:
  #   types: [completed, created, rerequested]
  check_suite:
    types: [completed]
  status: # No types needed for status, it triggers on any status update

jobs:
  deploy_on_signoff_check_success:
    name: Deploy to Hatchbox on Signoff
    runs-on: ubuntu-latest
    if: |
      startsWith(github.event.check_run.name, 'signoff') &&
      github.event.check_run.conclusion == 'success' &&
      github.event.check_run.pull_requests[0] != null
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.check_run.head_sha }} # Checkout the specific commit

      - name: Log Deployment Info
        run: |
          echo "Successful signoff check run detected: '${{ github.event.check_run.name }}' for commit ${{ github.event.check_run.head_sha }}."
          echo "Attempting to deploy commit ${{ github.event.check_run.head_sha }} using Hatchbox Deploy Action."
          if [ -z "${{ secrets.HATCHBOX_DEPLOY_KEY }}" ]; then
            echo "Error: HATCHBOX_DEPLOY_KEY secret is not set or is empty."
            echo "Please configure the HATCHBOX_DEPLOY_KEY secret in your repository settings."
            exit 1
          fi

      - name: Trigger Hatchbox Deployment
        uses: hatchboxio/github-hatchbox-deploy-action@v2
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
          sha: ${{ github.event.check_run.head_sha }} 